language: python
python:
  - '3.6.5'
node_js: '1.2'

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

install:
  - pip install pipenv
  - pip install invoke
  - inv install-requirements
  - source ./bin/functions/set_node_path.sh && setNodePath

script:
  - [ -d ./backend/__pycache__/ ] && rm -r ./backend/__pycache__/
  - inv lint-js
  - inv lint-py
  - inv test-py

after_success:
  - coveralls
