[tool.black]
line-length = 110
target-version = ['py36']
skip-string-normalization = true
include = '\backend'
#exclude = './backend/__pycache__/*'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | \./backend/__pycache__
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
