# Generated by Django 3.0.5 on 2020-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200309_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='room_id',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
