# Generated by Django 3.0.6 on 2020-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatchannel_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatchannel',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='room_id',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
