const DEFAULT_DRAGGABLE_CHAT_STYLE_CLASS = 'default-draggable-chat';

const DEFAULT_DRAGGABLE_CLASSNAME = 'default-react-draggable';

const DEFAULT_DRAGGABLE_HANDLE_CLASSNAME = 'default-react-draggable__default-handle';

const DEFAULT_DRAGGABLE_HANDLE = {
    CLASSNAME: DEFAULT_DRAGGABLE_HANDLE_CLASSNAME,
    IDENTIFIER: `.${DEFAULT_DRAGGABLE_HANDLE_CLASSNAME}`,
};

export {
    DEFAULT_DRAGGABLE_CHAT_STYLE_CLASS,
    DEFAULT_DRAGGABLE_CLASSNAME,
    DEFAULT_DRAGGABLE_HANDLE,
    DEFAULT_DRAGGABLE_HANDLE_CLASSNAME,
}
