# Generated by Django 3.0.6 on 2020-06-22 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('TexasHoldEm', 'TexasHoldEm')], max_length=50)),
                ('small_blind', models.IntegerField()),
                ('big_blind', models.IntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('hold_cards', models.CharField(max_length=50)),
                ('bet', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('Fold', 'Fold'), ('Call', 'Call'), ('Raise', 'Raise')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deck', models.CharField(choices=[('StandardSingle', 'StandardSingle')], default='StandardSingle', max_length=50)),
                ('deck_size', models.IntegerField()),
                ('last_round', models.CharField(choices=[('PreFlop', 'PreFlop'), ('Flop', 'Flop'), ('Turn', 'Turn'), ('River', 'River'), ('Showdown', 'Showdown')], max_length=50)),
                ('pot_size', models.IntegerField()),
                ('community_cards', models.CharField(blank=True, max_length=50, null=True)),
                ('banned_cards', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer', models.IntegerField()),
                ('players', models.ManyToManyField(to='poker.PokerPlayer')),
                ('poker_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.PokerRoom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
