# Generated by Django 3.0.6 on 2020-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerhand',
            name='banned_cards',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pokerhand',
            name='community_cards',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pokerhand',
            name='deck',
            field=models.CharField(choices=[('StandardSingle', 'StandardSingle')], default='StandardSingle', max_length=200),
        ),
    ]
