# Generated by Django 3.0.6 on 2020-07-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0001_initial'),
        ('poker', '0002_auto_20200622_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerplayer',
            name='gem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gem.Gem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokerplayer',
            name='hold_cards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
