# Generated by Django 3.0.6 on 2020-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_auto_20200728_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerroom',
            name='players',
            field=models.ManyToManyField(to='poker.PokerPlayer'),
        ),
    ]
