# Generated by Django 2.2.2 on 2020-03-02 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private'), ('Direct', 'Direct')], max_length=50)),
                ('messages', models.ManyToManyField(to='chat.Message')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
