# Generated by Django 2.2.2 on 2020-03-09 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200302_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='ChatChannel',
        ),
    ]
